# General
# -------
# Name of the environment.
env-name: "Highway-v0"

# Additional parameters for the environment (eg. bound for task sampling).
env-kwargs:
  low_cars: 10
  high_cars: 30
  low_att: 0
  high_att: 3

# Discount factor gamma.
gamma: 0.9

# Discount factor lambda used in "Generalized Advantage Estimation" (GAE).
gae-lambda: 1.0

# If "true", then the first order approximation of MAML is applied.
first-order: false

# Policy network
# --------------
# Number of hidden units in each layer.
hidden-sizes: [128, 128]

# Non-linear activation function to apply after each hidden layer.
nonlinearity: "tanh"

# Task-specific
# -------------
# Number of trajectories to sample for each task.
fast-batch-size: 20

# Number of gradient steps in the inner loop / fast adaptation.
num-steps: 10

# Step size for each gradient step in the inner loop / fast adaptation.
fast-lr: 0.01
